name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  swift-package-tests:
    name: Swift Package Tests
    uses: ./.github/workflows/swift-package-tests.yml
    with:
      timeout_minutes: 10

  demo-ui-tests:
    name: Demo App UI Tests
    uses: ./.github/workflows/demo-app-tests.yml
    with:
      build_timeout_minutes: 15
      test_timeout_minutes: 20
      continue_on_test_error: true
      run_tests: true

  # Build-only job (fallback when UI tests fail)
  demo-build-only:
    name: Demo App Build Check
    uses: ./.github/workflows/demo-app-tests.yml
    with:
      build_timeout_minutes: 15
      run_tests: false

  # Health check (dependency validation, etc.)
  health-check:
    name: Health Check
    runs-on: macos-15
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer
    
    - name: Validate Package.swift
      run: swift package describe --type json > package_info.json && cat package_info.json
    
    - name: Check for Swift warnings
      run: swift build 2>&1 | tee build_output.txt
    
    - name: Upload build output
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-output-${{ github.run_id }}
        path: build_output.txt
        retention-days: 3